### PR TITLE
Fix form submit validation

### PR DESCRIPTION
**Pull request by tumpio**
as discussed in https://github.com/pirxpilot/tags-input/pull/1

### CODE REVIEW

**Comment by tumpio** [comment]
I have another pull request coming for editing inserted tags:
https://github.com/tumpio/tags-input/commit/5c3177cea2a6e75cdc703b72c95065e944c15af5

**Comment by pirxpilot** [comment]
oops - sorry for the delay; I was on vacation and somehow missed a notification on this one. Will try to have a look this weekend. If you find some time please rebuild your branch not to include my merge commit, if not - no worries, I'll do that.

**Comment by tumpio** [comment]
> If you find some time please rebuild your branch not to include my merge commit, if not - no worries, I'll do that.

Sure! I spotted one other issue as well. It should not include 'value' property in MOVE_PROPS.

**Comment by tumpio** [comment]
Should be mergeable now.

**Comment by pirxpilot** [comment]
released in 2.1.7 - sorry it took so long

**Comment by tumpio** [comment]
No worries 👍

**Pull request merged**
